apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  url: https://github.com/YOUR_USERNAME/argocd-app-of-apps
  username: YOUR_GITHUB_USERNAME
  password: YOUR_GITHUB_PAT